# Generated by Django 5.1.3 on 2025-07-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_bouquet_options_alter_order_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bouquets/', verbose_name='Изображение'),
        ),
    ]
