# Generated by Django 5.1.3 on 2025-07-11 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_bouquet_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bouquet',
            options={'verbose_name': 'Букет', 'verbose_name_plural': 'Букеты'},
        ),
        migrations.AlterModelOptions(
            name='cartitem',
            options={},
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='bouquet_images/'),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bouquet',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
        migrations.AlterField(
            model_name='order',
            name='bouquets',
            field=models.ManyToManyField(to='main.bouquet'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
