# Generated by Django 5.1.3 on 2025-07-11 08:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_bouquet_options_alter_cartitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
    ]
